openapi: 3.0.0
info:
  title: IoT Authenticator
  version: 1.0.0
components:
  schemas:
    Ready:
      properties:
        status:
          type: string
        iotAuthenticator:
          type: object
          properties:
            version:
              type: string
            status:
              type: string
